runtime: php55
api_version: 1
threadsafe: true

skip_files:
- ^\.
- ^LICENSE
- ^README\.md

handlers:
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$
  application_readable: true
- url: /(.+\.(js|css))$
  static_files: \1
  upload: .+\.(js|css)$
- url: /(.+\.php)$
  script: \1
- url: /
  script: index.php