runtime: php55
api_version: 1
threadsafe: true

skip_files:
- ^(zerotwo)/index\.html$
- ^\.
- ^LICENSE
- ^README\.md

handlers:
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$
  application_readable: true
- url: /(.+\.(js|css))$
  static_files: \1
  upload: .+\.(js|css)$
- url: /(.+\.php)$
  script: \1
- url: /
  static_files: index.html
  upload: index.html
- url: /offline
  static_files: offline/index.html
  upload: offline/index.html
- url: /reinabot
  static_files: reinabot/index.html
  upload: reinabot/index.html
- url: /zerotwo
  script: zerotwo/index.php